import logging

from odoo import _, fields, models
from odoo.exceptions import UserError, ValidationError

_logger = logging.getLogger(__name__)


class MailMessage(models.Model):
    _inherit = "mail.message"

    user_vote = fields.Integer(
        string="User Vote",
        default=0,
        help="Vote status given by the user. 0: No vote, 1: Upvoted, -1: Downvoted.",
    )

    def _get_message_format_fields(self):
        """Extend the list of fields fetched by the base message_format."""

        fields_list = super()._get_message_format_fields()
        fields_list.extend(["user_vote", "llm_role", "body_json"])
        return fields_list

    def message_format(self):
        """Override to set is_note for LLM messages (bubble style)."""
        result = super().message_format()
        for message_data, message in zip(result, self):
            if message.llm_role:
                message_data["is_note"] = True
        return result

    def set_user_vote(self, vote_value):
        """Sets the user vote on this message, performing validation checks."""
        self.ensure_one()
        if self.llm_role not in ("assistant", "tool"):
            raise UserError(
                _(
                    "Voting is only allowed on messages generated by the assistant or a tool."
                )
            )
        if not isinstance(vote_value, int) or vote_value not in [-1, 0, 1]:
            raise ValidationError(
                _(
                    "Invalid vote value. Must be an integer: 1 (up), -1 (down), or 0 (none)."
                )
            )
        self.sudo().write({"user_vote": vote_value})
